### ISSUE TITLE
22-stlc.scala 

### ISSUE THREAD

**Issue by freddie-freeloader** [ps-tuebingen/PL1-2016#4]
[This](https://github.com/ps-tuebingen/PL1-2016/blob/master/lecturenotes/22-stlc.scala#L177-L184) looks suspicious to me:

```scala
case EliminateSum(e,fl,fr) => typeCheck(e,gamma) match {
  case SumType(left,right) => (typeCheck(fl,gamma), typeCheck(fr,gamma)) match {
    case (FunType(left,t1),FunType(right,t2)) =>
//                ^^^^             ^^^^^
//          `left` and `right` overshadow former definition
      if (t1 == t2) t1 else sys.error("type error: functions must have same return type")
    case _ => sys.error("type error in EliminateSum: ... functions")
}
```

Maybe rather define this:

```scala
  case SumType(left,right) => (typeCheck(fl,gamma), typeCheck(fr,gamma)) match {
    case (FunType(fromL,t1),FunType(fromR,t2)) =>
//                ^^^^^             ^^^^^
```

And then check for `left == fromL && right == fromR`.

**Comment by Blaisorblade** [comment]
I think you're right — the two `left` must match, and so the two `right`, but this code just shadows them. Can't fix it this second, I'll try to get to it ASAP.

**Comment by klauso** [comment]
Thanks for the bug report!

**Comment by Toxaris** [comment]
I think the following would also work:

~~~scala
case EliminateSum(e, fl, fr) => typeCheck(e, gamma) match {
  case SumType(left, right) => (typeCheck(fl, gamma), typeCheck(fr, gamma)) match {
    case (FunType(`left`,t1), FunType(`right`,t2)) =>
      if (t1 == t2) t1 else sys.error("type error: functions must have same return type")
    case _ => sys.error("type error in EliminateSum: ... functions")
}
~~~

See [SLS 8.1.5](http://www.scala-lang.org/files/archive/spec/2.11/08-pattern-matching.html#stable-identifier-patterns).

**Comment by Blaisorblade** [comment]
> I think the following would also work:

Agreed, I thought of that too. Maybe it'd work even for `t1`:
```
case (FunType(`left`,t1), FunType(`right`,`t1`)) => t1
```

Of course that's outside the Scala subset we're using in the course, but maybe @freddie-freeloader still finds that interesting 😉 
(Also, inlining guards is less helpful if trying to write good error messages, but that's not the main goal of this code).
